### ISSUE TITLE
Kanban board Setup

### ISSUE THREAD

**Issue by j-tee** [NatanimA/Reciepe-App#20]
# In This project:
- [A kanban board](https://github.com/users/NatanimA/projects/8/views/1) link
- we are a two-member team
    - @j-tee and @NatanimA 
 - Each task is a separate card that:
      - Has a descriptive title.
      - Has the number of points in the [Xpt] prefix. 
      - That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work.
      -  You shouldn't change the points after dividing up cards, even if the work takes longer.
      - Has a description of the task.

**Comment by Munsa1** [comment]
Hi @j-tee @NatanimA , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly ensure you have four `4` columns namely `To Do`, `In Progress`, `In Review`, and `Done` as this is a requirement. Please rename your existing columns accordingly and add a fourth column as well.
![image](https://user-images.githubusercontent.com/81932478/216935548-05a20079-da89-499e-b2bd-c50c54078d4f.png)






## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi team, 

To highlight 👍🏽 
✔️ All columns are added
✔️ Cards are complete
✔️ No errors

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
